### PR TITLE
do not require is_active field on model to sync local to set

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by rowanseymour** [comment]
Why is this change required? Elsewhere we make the assumption that syncable objects have this field.

**Comment by norkans7** [comment]
I think the other place is delete_local which can easily be overridden, is_active is not really required

**Comment by rowanseymour** [comment]
It's used in `sync_from_remote`. Is there a reason you can't add `is_active` to your model?

**Comment by norkans7** [comment]
Ahh right, I had missed that. sure I can add the field

**Pull request closed without merging**
